### ISSUE TITLE
linkWidgetBuilder slows down the performance and increase the memory consumption 

### ISSUE THREAD

**Issue by 90tamal90** [espresso3389/pdfrx#175] opened 2024-06-17 19:55 UTC
Sir, when add this code in the pdfView ....then the pdf view is stuck sometimes  and slows down the pdf view .....even some times the pdf view shows white pages ...long times ...and the ui becomes unresponsive.... please help me ....

When remove this code then all works fine .....  

      linkWidgetBuilder: (context, link, size) => MouseRegion(
                  cursor: SystemMouseCursors.click,
                  hitTestBehavior: HitTestBehavior.translucent,
                  child: GestureDetector(
                    behavior: HitTestBehavior.translucent,
                    child: InkWell(
                      onTap: () async {
                        // handle URL or Dest
                        if (link.url != null) {
      
                          print(link.url);
      
                          launchUrl(link.url!);
      
                           if (await isSecureUrl(link.url!)) {
      
                           }
      
                        } else if (link.dest != null) {
                        controller.goToDest(link.dest);
                        }
                      },
                      child: IgnorePointer(
                        child: Container(
                          color: Colors.blue.withOpacity(0.2),
                          width: size.width,
                          height: size.height,
                        ),
                      ),
                    ),
                  ),
                ),

**Comment by espresso3389** [comment] 2024-06-20 07:56
It depends on your machine spec (anyway I don't know what platform or what device you're using) and the PDF file.
How many links on your PDF files? Too many links? or just a little number of links?

No info. for your problem so far.

**Comment by 90tamal90** [comment] 2024-06-20 15:39
Here I run on Redmi note 10 pro mobile device ....and i test some other real devices .....

There are maximum 4 links in the PDF files ...

when add this linkWidgetBuilder ....in code ...then the pdf renders slow .....and pdf loading times becomes slow....

**Comment by espresso3389** [comment] 2024-06-20 15:51
How about the original example code of pdfrx? Does it work correctly?

**Comment by 90tamal90** [comment] 2024-06-20 16:01
Yes the original example code of pdfrx works correctly.... and the linkWidgetBuilder works well ....but the pdf loading time and the rendering time are increased when add linkWidgetBuilder

**Comment by 90tamal90** [comment] 2024-06-21 22:23
Sir, please help

**Comment by espresso3389** [comment] 2024-06-25 17:36
I want to clarify my position. I'm not a person who helps you. I'm just here to fix the issues.
So, don't ask me to help you. I don't have much time to help everyone come here.

The problem is that even people using devices older than yours does not complain about the speed. I'm not sure what's the cause of the issue...

**Comment by espresso3389** [comment] 2024-06-26 09:19
Hmm, why did you close the issue?

Do you have any further info?

**Comment by 90tamal90** [comment] 2024-06-26 09:22
I have tried to fix this issue

**Comment by 90tamal90** [comment] 2024-06-30 17:26
When there are a huge number of email IDs in PDF, the page loading time is too much... and is not scrollable the pdf page...
and the pdf view becomes stuck and unresponsive...

**Comment by espresso3389** [comment] 2024-07-01 04:35
Yes, such kind of PDF files may be heavy and slow on low spec devices...
In such case, linkWidgetBuilder or such kind of things that overlay widgets on PDF pages could not be used...

So, we need some kind of alternative approach and [pagePaintCallbacks](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/pagePaintCallbacks.html) + GestureRecognizer may be the last resort.

**Comment by 90tamal90** [comment] 2024-07-01 19:02
Sir, how to able with [pagePaintCallbacks + GestureRecognizer ] ... ??

**Comment by espresso3389** [comment] 2024-07-02 07:51
I didn't tested yet! But, in theory, it's possible. And, should we have the feature by default???

**Comment by 90tamal90** [comment] 2024-07-02 16:54
yes, sir..... please introduce this feature in default

**Comment by espresso3389** [comment] 2024-07-02 18:27
On 1.0.74, it contains the following changes:

- PdfViewerController.getPdfPageHitTestResult
- PdfViewerController.layout to get page layout

And, now you can implement canvas based link handling mechanism using them.

Firstly, you should have the following variable and functions:

```dart
  final _links = <int, List<PdfLink>>{};

  List<PdfLink>? _ensureLinksLoaded(PdfPage page) {
    final links = _links[page.pageNumber];
    if (links != null) return links;
    Future.microtask(() async {
      _links[page.pageNumber] = await page.loadLinks();
      controller.invalidate();
    });
    return null;
  }

  // Handle link taps
  void _handleLinkTap(Offset tapPosition) {
    final hitResult = controller.getPdfPageHitTestResult(
      tapPosition,
      useDocumentLayoutCoordinates: false,
    );
    if (hitResult == null) return;
    final links = _ensureLinksLoaded(hitResult.page);
    if (links == null) return;
    for (final link in links) {
      for (final rect in link.rects) {
        if (rect.containsOffset(hitResult.offset)) {
          if (link.url != null) {
            navigateToUrl(link.url!);
          } else if (link.dest != null) {
            controller.goToDest(link.dest);
          }
          return;
        }
      }
    }
  }

  // draw link highlights
  void _paintLinkHighlights(Canvas canvas, Rect pageRect, PdfPage page) {
    final links = _ensureLinksLoaded(page);
    if (links == null) return;

    final paint = Paint()
      ..color = Colors.blue.withOpacity(0.2)
      ..style = PaintingStyle.fill;
    for (final link in links) {
      for (final rect in link.rects) {
        final rectLink = rect.toRectInPageRect(page: page, pageRect: pageRect);
        canvas.drawRect(rectLink, paint);
      }
    }
  }
```

Then, PdfViewerParams should have the following changes:

```dart
viewerOverlayBuilder: (context, size) => [
  GestureDetector(
    behavior: HitTestBehavior.translucent,
    onTapUp: (details) =>
        _handleLinkTap(details.localPosition), // HERE: handle link taps
    ...
  ),
  ...
],
```

```dart
pagePaintCallbacks: [
  ... // some other callbacks
  _paintLinkHighlights, // HERE: you should add link highlights handler
],
```

I'm still thinking whether it is feasible for all the usages; it means this "may" or "may not" be a built-in feature in near future.

But you can now implement it by yourself. Anyway, try the code and give me any kind of feedback.

**Comment by HeropolisDa2ny** [comment] 2024-07-03 18:39
Well, it seems that your solution is working on an emulator or a computer but as soon as I put it on a physical device (Crosscall M5) the pages doesn't load. (There is a lot of link on every page)

![Screenshot_20240703-202246](https://github.com/espresso3389/pdfrx/assets/128067748/5fc2c5d6-1549-4fe8-951f-6c1fbde22335)
![Screenshot_20240703-202329](https://github.com/espresso3389/pdfrx/assets/128067748/84d71f64-5f19-4e38-9eda-54b766d5d100)

**Comment by espresso3389** [comment] 2024-07-03 18:42
Do you see any error on your debug console or Android's log? It seems to be severe memory situaton...

**Comment by espresso3389** [comment] 2024-07-03 18:48
To determine whether it is a memory issue or not, try to change [PdfViewerParams.onePassRenderingScaleThreshold](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/onePassRenderingScaleThreshold.html) to smaller value like 100 / 72.

**Comment by 90tamal90** [comment] 2024-07-03 18:50
Yes, I implemented this solution ....but when a large number of links are in the pdf ....like 200 links...then the pdf loading time is too much .....

Here is the screenshot...=====> 

![1720032438405](https://github.com/espresso3389/pdfrx/assets/170789007/af4bb24e-3ff0-442e-a856-1c95359b368e)
![1720032438382](https://github.com/espresso3389/pdfrx/assets/170789007/069148c9-3ce3-44b6-9af3-62e82fc60156)
![1720032438356](https://github.com/espresso3389/pdfrx/assets/170789007/2b948cd5-7398-485e-995b-834b1f43f28f)

**Comment by espresso3389** [comment] 2024-07-03 18:55
There seems roughly 1000 or more links inside a page. That's too much.

I think it's impossible to handle such a large number of links with such low spec device...

**Comment by HeropolisDa2ny** [comment] 2024-07-03 18:55
There is no error on the debug console but as soon as I close an reopen the page.
It seems to be a performance issue.

This error is massively spammed (I guess it is caught depending on the number of links)
```
[log] Null check operator used on a null value
      #0      PdfViewerController._state (package:pdfrx/src/widgets/pdf_viewer.dart:1625:40)
      #1      PdfViewerController.invalidate (package:pdfrx/src/widgets/pdf_viewer.dart:1924:24)
      #2      _ItemPdfState._ensureLinksLoaded.<anonymous closure> (package:_/shared_system/widgets/pdf/pdf.item.dart:25:19)
      <asynchronous suspension>
```

Changing the `onePassRenderingScaleThreshold` doesn't change anything.
Also scrolling down to load more and scrolling up make also the previous loaded pages unavailable.

**Comment by HeropolisDa2ny** [comment] 2024-07-03 18:57
> There seems roughly 1000 or more links inside a page. That's too much.
> 
> I think it's impossible to handle such a large number of links with such low spec device...

There is around 70 links inside a page

**Comment by 90tamal90** [comment] 2024-07-03 19:02
> There seems roughly 1000 or more links inside a page. That's too much.
> 
> I think it's impossible to handle such a large number of links with such low spec device...

But, I have tested some high-end devices ...there is the same problem...  when link is more like 40 to 100 then the loading time of pdf pages is too much.... and sometimes the UI is going to freeze

**Comment by espresso3389** [comment] 2024-07-03 19:15
Please count the total number of light-blue rectangles. It's the actual link count.

**Comment by 90tamal90** [comment] 2024-07-03 19:22
Sir, this is my app in PlayStore..... with this rich PDFrx package...
You can observe this issue 

**Link**: [https://play.google.com/store/apps/details?id=com.kodexlab.documentreader.manager.viewer](url)

**Comment by HeropolisDa2ny** [comment] 2024-07-03 19:27
@espresso3389 it is the only package on flutter that allows this kind of system, we should try to find a solution to handle hundred or thousands links in a PDF

**Comment by espresso3389** [comment] 2024-07-03 19:30
Currently, the features like text selection and link handling are designed in the way to keep the API surface clean and easy. And the performance/memory consumption are not so seriously profiled.

So we need some kind of profiling on these features to optimize them for such kind of heavy PDF files...

**Comment by reddeath1** [comment] 2024-07-04 08:53
final hitResult = Pdfcontroller.getPdfPageHitTestResult(
      tapPosition,
      useDocumentLayoutCoordinates: false,
    );


using this how can I get exact paragraph from the pointer. this will help to generate weblink from a specific paragraph.

**Comment by espresso3389** [comment] 2024-07-04 09:20
@reddeath1

It's a little off topic here but I want to explain the things here:

[PdfViewerController.getPdfPageHitTestResult](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerController/getPdfPageHitTestResult.html) does hit-test against pages and returns the corresponding point in page coordinates. It has nothing to do with paragraphs/links.

To get text paragraphs/links, use [PdfPage.loadText](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPage/loadText.html), [PdfPage.loadLinks](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfPage/loadLinks.html)

**Comment by reddeath1** [comment] 2024-07-04 09:34
Thank you such method  Pdfcontroller.getPdfPageHitTestResult() is well aligned to what I want to achieve. 

I think getting .rects, of a specific area I can able to get text of the specific coordinates. what do you think or any suggestions.

 final hitResult = Pdfcontroller.getPdfPageHitTestResult(
      tapPosition,
      useDocumentLayoutCoordinates: false,
    );

    var link = await hitResult?.page.loadLinks();
    print(link!.last.rects);

[PdfRect(left: 57.042015075683594, top: 555.2490234375, right: 191.884521484375, bottom: 548.1990356445312)]

**Comment by espresso3389** [comment] 2024-07-04 09:38
@reddeath1 See the [example code](https://github.com/espresso3389/pdfrx/issues/175#issuecomment-2204022289) above. Everything is illustrated in the code. __Please note that I'm not your tutor or such. Please read the documents and do your job by yourself.__

**Comment by reddeath1** [comment] 2024-07-04 09:44
Thank you again. I understand your position, but since you are the one who created this plugin, you must have an idea of what needs to be done without reviewing the entire codebase. Trust me, if it were easy, I wouldn't be asking this question. I saw an opportunity and thought I could leverage it to achieve what I wanted most.

**Comment by espresso3389** [comment] 2024-07-04 09:52
@reddeath1 I have my own paid job. pdfrx is completely free and I don't get any money (except some paid me a little using GitHub sponsors). In this week, pdfrx support took me about 3 days or more. How can I live without money? Do you really understand my situation??

**Comment by reddeath1** [comment] 2024-07-04 10:25
Thank you brother I understand,

You're doing a great job, please don't mind me.

Best Regards
Frank Galos
Mobile| Web | Desktop Apps Developer

**Comment by espresso3389** [comment] 2024-07-06 09:47
1.0.75 introduces a new parameter for `PdfPage.loadLinks` named `compact`.
It may increase the link processing CPU load, but it reduces memory usage by `PdfLink` instances.
I'm not sure how it reduces the total memory usage but please try it.

```dart
// The usage is very simple; passcompact: true to loadLinks method
final links = await page.loadLinks(compact: true);
```

**Comment by 90tamal90** [comment] 2024-07-06 17:38
final links = await page.loadLinks(compact: true);


Is this in linkWidgetBuilder???

**Comment by espresso3389** [comment] 2024-07-06 18:14
I'm working on a brand new link handling mechanism based on the technology above.
You can check the current code on aa83d243fce6f45404c7a19fbcd1b3917c02b54c.

**Comment by 90tamal90** [comment] 2024-07-06 18:48
Ok, sir ...

> I'm working on a brand new link handling mechanism based on the technology above. You can check the current code on [aa83d24](https://github.com/espresso3389/pdfrx/commit/aa83d243fce6f45404c7a19fbcd1b3917c02b54c).
> 
> ```dart
> linkHandlerParams: PdfLinkHandlerParams(
>   onLinkTap: (link) {
>     if (link.url != null) {
>       navigateToUrl(link.url!);
>     } else if (link.dest != null) {
>       controller.goToDest(link.dest);
>     }
>   },
> ),
> ```

Ok Sir 👍

**Comment by espresso3389** [comment] 2024-07-08 07:38
I've done some rebase and force-push so the commit referenced above is gone :(

But the good news is that 1.0.76 contains the feature. You can now easily use the feature!

**Comment by espresso3389** [comment] 2024-07-08 07:55
To test handling of thousands of links, I prepared a PDF:
[1000links.pdf](https://github.com/user-attachments/files/16124413/1000links.pdf)

**Comment by espresso3389** [comment] 2024-07-08 08:18
**Disclaimer: The test is running on Windows PC with Ryzen 9 7950X3D with 96GB memory; I think it could not be operatable on normal smartphones.**

## First open

When I just opened the first page (and 2nd page) on the screen, the memory consumption seems acceptable and the viewer shows the page in "acceptable" time.

![image](https://github.com/espresso3389/pdfrx/assets/1311400/ed78361c-6478-43d8-8a6c-5416442beb86)

![image](https://github.com/espresso3389/pdfrx/assets/1311400/e4ae7275-801f-4fbd-b134-f989462feaec)

## Scrolling operation

Then, scroll down to the end of document and get back to the first page.
The scrolling operation makes the viewer very busy (for certain operation) and consumes much memory:

![image](https://github.com/espresso3389/pdfrx/assets/1311400/fa40a4c6-1f27-43c6-92a7-a044f277a761)

![image](https://github.com/espresso3389/pdfrx/assets/1311400/8bb93ebd-1165-4c9a-a3d7-ead8849e46a9)

## After considerable period

After certain period, the viewer resumed to the normal operation. And unused class instances are GC-ed:

![image](https://github.com/espresso3389/pdfrx/assets/1311400/8c2c84dd-e35f-4e95-85d1-af9f15503d3b)

**Comment by espresso3389** [comment] 2024-07-08 08:32
The experiment result explains that the most memory consuming thing is PdfRect. And the second is PdfLink (that is the point of the issue).

And, the memory consumption makes GC so busy for very long time. But after GC, the memory consumption get back to normal, it is slightly larger than the first state, but it seems acceptable memory consumption.

The PdfRect structure is very simple but in theory it takes at least 32 byte/instance.

![image](https://github.com/espresso3389/pdfrx/assets/1311400/133a0408-5aa6-4989-b8cb-a8c538370ba1)

And the profiler shows it is amost 47 bytes/instance; there seems 16 bytes overhead per instance but it is anyway very understandable for memory management; I guess that all the memory chunk has 16-byte alignment and 32 bytes+control block can be aligned to 48 bytes.

**Comment by espresso3389** [comment] 2024-07-08 13:23
I've found a very beginner level coding issue on 1.0.76; now 1.0.77 fixes the issue and now the behavior is much better now:

https://photos.app.goo.gl/2yFW1AedzRKxMDdu8

The video is recorded on Nothing Phone (2a); MediaTek Dimensity 7200 Pro+8GB+128GB.

**Comment by espresso3389** [comment] 2024-07-08 13:25
@90tamal90 @HeropolisDa2ny Try 1.0.77.

**Comment by espresso3389** [comment] 2024-07-08 13:48
README.md now has a section for the new link handling usage:

https://github.com/espresso3389/pdfrx?tab=readme-ov-file#pdf-link-handling

**Comment by HeropolisDa2ny** [comment] 2024-07-08 17:46
> README.md now has a section for the new link handling usage:
> 
> https://github.com/espresso3389/pdfrx?tab=readme-ov-file#pdf-link-handling

From what I've tried ~50 links by pages it is loading the pages really quickly so it seems matching correctly the needs.
Tested on Crosscall M5 device.

**Comment by 90tamal90** [comment] 2024-07-09 16:16
> @90tamal90 @HeropolisDa2ny Try 1.0.77.

Yes, I have tried this version and the 100 links with pages are loading a bit faster than the previous version .... 

here I share a screen record ...I have tested this in real device ..Redmi note 10 Pro (6gb ram)...

https://github.com/espresso3389/pdfrx/assets/170789007/387ceb74-5885-41f8-8b2a-b8bc54a85280


Here  how am I able to   onTapUp:  =>  
I use OnTap method but in link i want onTapUp
              

                linkHandlerParams: PdfLinkHandlerParams(
                                onLinkTap: (link) async {
                                  // handle URL or Dest
                                  if (link.url != null) {
                                    // TODO: implement your own isSecureUrl by yourself...
                                  //   if (await isSecureUrl(link.url!)) {
                                  // launchUrl(link.url!);
                                  // }
                                    navigateToUrl(context, link.url!);
                                  } else if (link.dest != null) {
                                  controller.goToDest(link.dest);
                                  }
                                },
                              ),

**Comment by espresso3389** [comment] 2024-07-09 16:23
@90tamal90 
For the speed, I think it's almost the fastest implementation we can do now. So if it's still slow on certain device, the device is too slow or the PDF is too complex.

> Here how am I able to onTapUp: =>
> I use OnTap method but in link i want onTapUp

PdfLinkHandlerParams's onLinkTap is actually [implemented using onTapUp](https://github.com/espresso3389/pdfrx/blob/df7419d05831491909614a2295e4b74ed372ccbe/lib/src/widgets/pdf_viewer.dart#L2117). We could not use onTapDown for such cases because it conflicts with other gestures.

**Comment by 90tamal90** [comment] 2024-07-09 16:27
> @90tamal90 For the speed, I think it's almost the fastest implementation we can do now. So if it's still slow on certain device, the device is too slow or the PDF is too complex.
> 
> > Here how am I able to onTapUp: =>
> > I use OnTap method but in link i want onTapUp
> 
> PdfLinkHandlerParams's onLinkTap is actually [implemented using onTapUp](https://github.com/espresso3389/pdfrx/blob/df7419d05831491909614a2295e4b74ed372ccbe/lib/src/widgets/pdf_viewer.dart#L2117). We could not use onTapDown for such cases because it conflicts with other gestures.

But here I am using onTap now not working .....how to fix this ....
here is my code 

              viewerOverlayBuilder: (context, size) => [
                              GestureDetector(
                                behavior: HitTestBehavior.translucent,
              
                                // onTapUp: (details) =>
                                //     _handleLinkTaps(details.localPosition),  // HERE: handle link taps
              
                                onDoubleTap: () {
                                  controller.zoomUp(loop: true);
                                },
                                
                                onTap: () async {
              
                                  if(!_isTextSelectionEnabled) {
                                     _toggleVisibility();
                                  } else {
                                    setState(() {
                                      _isTextSelectionEnabled = false;
                                      _enableTextSelection = false;
              
                                      _textSelectionResetTimer = Timer(const Duration(milliseconds: 200), () {
                                        setState(() {
                                          _enableTextSelection = true;
                                        });
                                      });
              
                                    });
                                  }
              
                                },
              
                                child: IgnorePointer(
                                  child: SizedBox(width: size.width, height: size.height),
                                ),
                              ),

**Comment by espresso3389** [comment] 2024-07-09 16:31
Oh, please just remove onTapUp from viewerOverlayBuilder. It's now included on the pdfrx.
Now you don't need [the code explained above](https://github.com/espresso3389/pdfrx/issues/175#issuecomment-2204022289).

**Comment by 90tamal90** [comment] 2024-07-09 16:32
> @90tamal90 For the speed, I think it's almost the fastest implementation we can do now. So if it's still slow on certain device, the device is too slow or the PDF is too complex.
> 
> > Here how am I able to onTapUp: =>
> > I use OnTap method but in link i want onTapUp
> 
> PdfLinkHandlerParams's onLinkTap is actually [implemented using onTapUp](https://github.com/espresso3389/pdfrx/blob/df7419d05831491909614a2295e4b74ed372ccbe/lib/src/widgets/pdf_viewer.dart#L2117). We could not use onTapDown for such cases because it conflicts with other gestures.

Yes, I think this pdf is very complex....so this pdf is not open fast....but other pdfs is loading is very fast with links ......but I have tested with [Android PdfViewer](https://github.com/DImuthuUpe/AndroidPdfViewer), for this particular PDF...then in this library, the pdf is loading with links very fast

**Comment by espresso3389** [comment] 2024-07-09 16:36
@90tamal90 Please ensure that you should remove all the example codes; especially, _ensureLinksLoaded has a critical bug that makes the loading so slow.

**Comment by 90tamal90** [comment] 2024-07-09 16:38
> Oh, please just remove onTapUp from viewerOverlayBuilder. It's now included on the pdfrx. Now you don't need [the code explained above](https://github.com/espresso3389/pdfrx/issues/175#issuecomment-2204022289).

I remove all previous code ...and onTapUp ....but viewerOverlayBuilder's GestureDetector and the linkHandlerParams GestureDetector are conflicted each other then viewerOverlayBuilder's GestureDetector is not working .......

**Comment by 90tamal90** [comment] 2024-07-09 16:47
> On your code, viewerOverlayBuilder's GestureDetector has three handlers, onTapUp, onDoubleTap, and onTap. I think you can safely remove onTapUp. Which one is conflicting with PdfLinkHandlerParams? onDoubleTap or onTap?

the onTap is not working ......in viewerOverlayBuilder .....

here my updated code , still the onTap is not working 

                viewerOverlayBuilder: (context, size) => [
                                GestureDetector(
                                  behavior: HitTestBehavior.translucent,
                                  
                                  onDoubleTap: () {
                                    controller.zoomUp(loop: true);
                                  },
                
                                  onTap: () async {
                                    if(!_isTextSelectionEnabled) {
                                       _toggleVisibility();
                                    } else {
                                      setState(() {
                                        _isTextSelectionEnabled = false;
                                        _enableTextSelection = false;
                
                                        _textSelectionResetTimer = Timer(const Duration(milliseconds: 200), () {
                                          setState(() {
                                            _enableTextSelection = true;
                                          });
                                        });
                
                                      });
                                    }
                                  },
                
                                  child: IgnorePointer(
                                    child: SizedBox(width: size.width, height: size.height),
                                  ),
                                ),

**Comment by espresso3389** [comment] 2024-07-09 17:29
Yeah, it's very natural that onTap is not propagated to viewerOverlayBuilder because it's already handled by GestureDetector associated to PdfLinkHandlerParams internally.

In theory, if we disable PdfLinkHandlerParams's GestureDetector (there still no way to do that), your onTap can be called. But if then, we should call some method to handle link tap manually (it's not also prepared on API)...

OK, I understood the issue correctly. I'll add some more changes to PdfLinkHandlerParams and others to make it possible to use your own onTap handler.

**Comment by 90tamal90** [comment] 2024-07-10 16:51
> 1.0.80 has a breaking change on [PdfViewerParams.viewerOverlayBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/viewerOverlayBuilder.html).
> 
> It now has third parameter named `handleLinkTap` and if you use`[GestureDetector](https://api.flutter.dev/flutter/widgets/GestureDetector-class.html)` on `viewerOverlayBuilder`, you should manually wire `onTapUp` to `handleLinkTap`.
> 
> See [PdfViewerParams.viewerOverlayBuilder](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/viewerOverlayBuilder.html) and https://github.com/espresso3389/pdfrx/blob/2e67ee521b1295e321413de3dd9ad763ef99ee88/example/viewer/lib/main.dart#L274C21-L294C25.
> 
> ```dart
> viewerOverlayBuilder: (context, size, handleLinkTap) => [
>   //
>   // Double-tap to zoom
>   //
>   GestureDetector(
>     behavior: HitTestBehavior.translucent,
>     // If you use GestureDetector on viewerOverlayBuilder, it breaks link-tap handling
>     // and you should manually handle it using onTapUp callback
>     onTapUp: (details) {
>       handleLinkTap(details.localPosition);
>     },
>     onDoubleTap: () {
>       controller.zoomUp(loop: true);
>     },
>     // Make the GestureDetector covers all the viewer widget's area
>     // but also make the event go through to the viewer.
>     child: IgnorePointer(
>       child:
>           SizedBox(width: size.width, height: size.height),
>     ),
>   ),
> ```

OK ....Now the "onTap" works perfectly in viewerOverlayBuilder with the 1.0.80  version...
Thanks ...👌🙏

**Closed** 2024-07-10 17:02 UTC
Labels: feature request, enhancement
