### ISSUE TITLE
Fail to run in Flutter 3.27.0

### ISSUE THREAD

**Issue by stephane-couget** [espresso3389/pdfrx#275] opened 2024-12-13 09:03 UTC
**Describe the bug**
After update Flutter version to 3.27.0 the app got this error.

**To Reproduce
Steps to reproduce the behavior:**

    Update the app to 3.27.0
    Run the app
    See error

**Expected behavior**
The app run normally

**copy screen**

```
* What went wrong:
Execution failed for task ':pdfrx:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `/home/sco/.pub-cache/hosted/pub.dev/pdfrx-1.0.97/android/.cxx/Debug/3r6f6f23/arm64-v8a'
  [1/2] Building CXX object shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o
  FAILED: shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o 
  /home/sco/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=aarch64-none-linux-android21 --sysroot=/home/sco/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot -DDART_SHARED_LIB -Dpdfrx_EXPORTS -I/home/sco/.pub-cache/hosted/pub.dev/pdfrx-1.0.97/android/.lib/latest/include -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fno-limit-debug-info  -fPIC -MD -MT shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o -MF shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o.d -o shared/CMakeFiles/pdfrx.dir/pdfium_interop.cpp.o -c /home/sco/.pub-cache/hosted/pub.dev/pdfrx-1.0.97/src/pdfium_interop.cpp
  In file included from /home/sco/.pub-cache/hosted/pub.dev/pdfrx-1.0.97/src/pdfium_interop.cpp:2:
  In file included from /snap/flutter/current/usr/include/c++/9/thread:39:
  /snap/flutter/current/usr/include/c++/9/memory:121:25: error: cast from pointer to smaller type 'uintptr_t' (aka 'unsigned int') loses information
    const auto __intptr = reinterpret_cast<uintptr_t>(__ptr);
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      /home/sco/Android/Sdk/cmake/3.18.1/bin/ninja \
        -C \
        /home/sco/.pub-cache/hosted/pub.dev/pdfrx-1.0.97/android/.cxx/Debug/3r6f6f23/arm64-v8a \
        pdfrx
    from /home/sco/.pub-cache/hosted/pub.dev/pdfrx-1.0.97/android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

```

**flutter doctor -v**
```
[✓] Flutter (Channel stable, 3.27.0, on Manjaro Linux 6.12.1-4-MANJARO, locale fr_FR.utf8)
    • Flutter version 3.27.0 on channel stable at /home/sco/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 8495dee1fd (il y a 2 jours), 2024-12-10 14:23:39 -0800
    • Engine revision 83bacfc525
    • Dart version 3.6.0
    • DevTools version 2.40.2

[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
    • Android SDK at /home/sco/Android/Sdk
    • Platform android-35, build-tools 35.0.0
    • Java binary at: /home/sco/tools/android-studio/jbr/bin/java
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)
    • All Android licenses accepted.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 10.0.0-4ubuntu1
    • cmake version 3.16.3
    • ninja version 1.10.0
    • pkg-config version 0.29.1

[✓] Android Studio (version 2024.2)
    • Android Studio at /home/sco/tools/android-studio
    • Flutter plugin version 83.0.3
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 21.0.3+-12282718-b509.11)

[✓] Connected device (2 available)
    • SM T970 (mobile) • R52R40AJJ6R • android-arm64 • Android 13 (API 33)
    • Linux (desktop)  • linux       • linux-x64     • Manjaro Linux 6.12.1-4-MANJARO

[✓] Network resources
    • All expected network resources are available.
```

Best regards,

**Comment by espresso3389** [comment] 2024-12-13 09:30
Duplicate of #243.
And, I don't know the exact cure for the issue. It's not a problem of pdfrx and many other Flutter projects suffer from this.
Just clean everything; really everything. Flutter, Gradle, and others before rebuilding.

**Closed by espresso3389** 2024-12-13 09:30 UTC

**Comment by stephane-couget** [comment] 2024-12-13 09:38
Thanks to #243, I see a common point which is that Flutter is installed with Snap. I'll test with other installers to see if it changes anything. Thank you for the feedback.
