### ISSUE TITLE
Impossible to render/view a pdf

### ISSUE THREAD

**Issue by HeropolisDa2ny** [espresso3389/pdfrx#178] opened 2024-06-19 12:16 UTC
Hello,

I'm trying to render a simple PDF however it is impossible to load it since I'm getting a `libpdfium` error

```
PdfViewer.uri(
      Uri.parse('https://www.clickdimensions.com/links/TestPDFfile.pdf'),
      controller: PdfViewerController(),
      params: PdfViewerParams(
          errorBannerBuilder: (context, error, stacktrace, ref) {
        log(error.toString());
        log(stacktrace.toString());

        return Container();
      }),
    );
```
```
PdfViewer.data(
      data,
      sourceName: 'damn',
      params: PdfViewerParams(
          errorBannerBuilder: (context, error, stacktrace, ref) {
        log(error.toString());
        log(stacktrace.toString());

        return Container();
      }),
      key: key,
    );
```

```
[log] Invalid argument(s): Failed to load dynamic library 'libpdfium.so': dlopen failed: library "libpdfium.so" not found
[log] #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      pdfium (package:pdfrx/src/pdfium/pdfrx_pdfium.dart:31:43)
#3      pdfium (package:pdfrx/src/pdfium/pdfrx_pdfium.dart)
#4      _init.<anonymous closure> (package:pdfrx/src/pdfium/pdfrx_pdfium.dart:46:7)
#5      using (package:ffi/src/arena.dart:124:31)
#6      _init (package:pdfrx/src/pdfium/pdfrx_pdfium.dart:38:3)
#7      PdfDocumentFactoryImpl.openCustom (package:pdfrx/src/pdfium/pdfrx_pdfium.dart:150:5)
#8      PdfDocument.openCustom (package:pdfrx/src/pdf_api.dart:203:35)
```

Flutter version:

Flutter 3.22.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 761747bfc5 (2 weeks ago) • 2024-06-05 22:15:13 +0200
Engine • revision edd8546116
Tools • Dart 3.4.3 • DevTools 2.34.3

**Comment by espresso3389** [comment] 2024-06-19 12:19
What platform do you run the code on?

**Comment by HeropolisDa2ny** [comment] 2024-06-19 12:26
Also I cannot run under the latest version because of rxdart >=0.26.0 <0.28.0 used by just audio (on both pdfrx ^1.0.69 and just_audio ^0.9.38, version solving failed.) but I havent seen any fix related to `libpdfium` in your last commits.

**Comment by espresso3389** [comment] 2024-06-20 07:53
For rxdart version conflict, use [dependency_overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) to pin rxdart to certain version such as 0.27.0.

**Comment by espresso3389** [comment] 2024-06-25 17:28
I cannot see what's your environment. M1 Mac or such?
Could you please show me your `flutter doctor -v`?

And, did you run the code on actual device?

**Comment by HeropolisDa2ny** [comment] 2024-07-02 15:59
Sorry for the long delay I wasn't able to give you response before.

I upgrade your package to `pdfrx: ^1.0.73`

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pdfrx:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libpdfium.so' from inputs:
      - /Users/_/Projects/front-flutter/build/pdfrx/intermediates/merged_jni_libs/debug/out/arm64-v8a/libpdfium.so
      - /Users/_/Projects/front-flutter/build/pdfrx/intermediates/cxx/Debug/3515273s/obj/arm64-v8a/libpdfium.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```

<details>
  <summary>Flutter doctor</summary>

```
/Users/_/development/flutter/bin/flutter doctor --verbose
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale en-MX)
    • Flutter version 3.22.2 on channel stable at /Users/_/development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 761747bfc5 (4 weeks ago), 2024-06-05 22:15:13 +0200
    • Engine revision edd8546116
    • Dart version 3.4.3
    • DevTools version 2.34.3

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at /Users/_/Library/Android/sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A507
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.90.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.90.0

[✓] Connected device (5 available)
    • Core M5 (mobile)                • ec4ad0bb                  • android-arm64  • Android 12 (API 31)
    • macOS (desktop)                 • macos                     • darwin-arm64   • macOS 14.5 23F79 darwin-arm64
    • Mac Designed for iPad (desktop) • mac-designed-for-ipad     • darwin         • macOS 14.5 23F79 darwin-arm64
    • Chrome (web)                    • chrome                    • web-javascript • Google Chrome 126.0.6478.127

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```
</details>

**Comment by espresso3389** [comment] 2024-07-02 16:20
For multiple libpdfium.so error, see https://github.com/espresso3389/pdfrx/issues/8#issuecomment-1898225027

**Comment by espresso3389** [comment] 2024-07-02 16:35
Duplicate of #8

**Closed by espresso3389** 2024-07-02 16:35 UTC
Labels: duplicate
