### ISSUE TITLE
 Is text selection possible on PDF?

### ISSUE THREAD

**Issue by mlican** [espresso3389/pdfrx#4] opened 2023-12-13 08:09 UTC
I'm interested in using the [pdfrx] for my Android application. I would like to know if it supports text selection functionality. Specifically, I would like to implement a feature where users can long-press on a PDF document and select/highlight text.

I've explored the documentation and codebase, but I couldn't find any specific information regarding text selection. Could you please clarify if this feature is supported or provide any guidance on how to achieve it?

Thank you for your assistance!

**Comment by espresso3389** [comment] 2023-12-13 10:19
I'm still working on that but on GitHub, you can see the "initial" and "draft" design of the underlying text extraction API and it's usage example (not yet finished);

- [PdfPageText](https://github.com/espresso3389/pdfrx/blob/master/lib/src/pdfrx_api.dart#L221)
- [example usage](https://github.com/espresso3389/pdfrx/blob/master/example/lib/main.dart#L45)

Basically, underlying API is almost freezed (not to be changed) but I should integrate text selection GUI code into PdfViewer widget anyway (I'm just working and I will take 1 week to finish I guess).

Task lists so far:

- On Desktop, if I use [SelectionArea](https://api.flutter.dev/flutter/material/SelectionArea-class.html) widget for text selection purpose, it blocks pan-to-scroll
- Search popup (how to customize or such)
- Hyperlink handling

Anyway, I'm still open to any opnions and suggestions so please feel free to ask anything to me!

**Comment by espresso3389** [comment] 2023-12-13 10:21
Oh, you can see the current progress on the demo site: https://espresso3389.github.io/pdfrx/

**Comment by mlican** [comment] 2023-12-14 03:26
> [0.2.1](https://pub.dev/packages/pdfrx/versions/0.2.1) is a new release that stabilizes the API;
> 
> * example code has possible demonstration code to select texts

Inaccurate Cursor Position and Selector Shaking Issue during PDF Zoom on Android.

I have noticed an issue while zooming in on PDF documents on Android. The cursor position for text selection seems to be inaccurate, and there is also a shaking phenomenon observed with the selector. This affects the precision and usability of selecting text within the PDF viewer. It would be greatly appreciated if this issue could be addressed and resolved. Thank you!

**Comment by espresso3389** [comment] 2023-12-14 03:41
I understood that. I'm still working on it.

**Comment by Aruljebaraj** [comment] 2023-12-20 11:56
Badly waiting for this feature

**Comment by espresso3389** [comment] 2023-12-21 17:44
Still work in progress; but I'm struggling with Flutter's text selection mechanism...

https://github.com/espresso3389/pdfrx/assets/1311400/3fe672d7-df48-4cb0-a586-448ac45e79ac

**Comment by mlican** [comment] 2023-12-22 02:06
> Still work in progress; but I'm struggling with Flutter's text selection mechanism...
> 
>  Video.mp4

It looks great!  I’m looking forward to this feature.

**Comment by espresso3389** [comment] 2023-12-24 16:41
It's breedingly experimental and still not almost usable on Desktop platforms (though it's working), but you can see the current behavior with the git's latest version (38bbd6480c9d95d306b6b9eb8fe3a8aa91d745e7):

```dart
PdfViewer.uri(
              Uri.parse(kIsWeb
                  ? 'assets/hello.pdf'
                  : 'https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf'),
              controller: controller,
              displayParams: PdfViewerParams(
                maxScale: 8,
                // FIXME: if it's desktop, text selection feature is not correctly working now.
                // Even on mobile platforms, it is still very experimental. Please take extreme care when using it.
                enableTextSelection: !_isDesktop,
              ),
            ),
...
```

Current issues:

- It's slow; rendering of selection area is currently _intentionally_ delayed from the actual scroll/zoom
- Desktop version would not allow you to pan if your cursor is on SelectionArea widget (currently, the widget is filled with light-cyan color)

The reason of such issues is very simple, current Flutter API does not assume such kind of selection mechanism

- If we directly use SelectionArea/Selectable on Interactive Viewer, the selection handles and popups are zoom-in/-out by InteractiveViewer
- SelectionArea requires us to build many Selectable widgets to make the texts selectable

I'm still investigating the way to improve the performance but anyway I should post some report on Flutter issues.

**Comment by espresso3389** [comment] 2023-12-24 16:45
And, the demo video here:

https://github.com/espresso3389/pdfrx/assets/1311400/1fd07aa7-c5b5-4260-86e9-f7ec82d5fac8

**Comment by mlican** [comment] 2023-12-25 02:48
Thank you very much for your efforts on this feature. I still have a question. How to use the mouse wheel on the desktop to scroll PDF instead of zooming?

**Comment by espresso3389** [comment] 2023-12-25 03:06
> How to use the mouse wheel on the desktop to scroll PDF instead of zooming?

Good question!
Frankly speaking, I don't know. InteractiveViewer assigns mouse wheel to zooming :(
Just reading InteractiveViewer's document does not answer to the question.

[#114280](https://github.com/flutter/flutter/pull/114280) seems related to the question, but reading the thread does not explain me what to do.

Any ideas?

**Comment by espresso3389** [comment] 2023-12-25 11:06
For scroll by mouse-wheel issue, see #10; the issue is for text selection only.

**Comment by mlican** [comment] 2023-12-31 14:17
Is there a way to optimize text selection in a PDF with a dual-column layout?

**Comment by espresso3389** [comment] 2023-12-31 14:35
@mlican 
> Is there a way to optimize text selection in a PDF with a dual-column layout?

It's not a easy way to correctly handle PDF's embedded text.

In theory, the reading order has to be implied by the embedded text content, but in reality, PDF generator software embeds texts based on their own algorithm.

Frankly speaking, every PDF reader software is struggling with such almost "broken" text structure and there is no correct way to restore the original author's intention. Some uses AI or such to restore them.

So, anyway, I don't intend to build perfect text extraction mechanism but some acceptable text search and extraction.

**Comment by espresso3389** [comment] 2023-12-31 14:44
As a side note, for pdfium, I'm now using [a determinisitc algorithm](https://github.com/espresso3389/pdfrx/blob/master/lib/src/pdfium/pdfrx_pdfium.dart#L498) to restore text structure **that fits well** with Flutter's SelectionArea.

Flutter's SelectionArea is just another beast that I should battle with. It's basically designed to select normal hand-crafted Text widgets but PDF's embedded texts are neither so simple nor sophisticated and Flutter's SelectionArea would not accept them without normalizing the embedded texts.

**Comment by yhyh0** [comment] 2024-01-12 07:43
@espresso3389 Thanks for the work. It helps a lot. Why has this feature been removed from the latest code though?

**Comment by espresso3389** [comment] 2024-01-12 08:25
@yhyh0 Yes, it is removed because it's too slow and could not be used in realistic apps.
I'm now rewriting new text selection code that does not depend on Flutter's Selectable.

**Comment by mlican** [comment] 2024-01-12 09:05
> @yhyh0 Yes, it is removed (at 0.4.3 [ab9c9d0](https://github.com/espresso3389/pdfrx/commit/ab9c9d00546f05d56203c8b1b43986a36a8079f2)) because it's too slow and could not be used in realistic apps. I'm now rewriting new text selection code that does not depend on Flutter's Selectable.
> 
> The last code is on [pdf_widget.dart on 70a92e](https://github.com/espresso3389/pdfrx/blob/70a92e2b4d9ad24b13209b712b4afa8ab6fa53da/lib/src/pdf_widgets.dart#L1068) and it may hopefully work with the latest pdfrx...

I feel that the text selection performance I made based on Flutter's Selectable is pretty good. The following is a display of my application.

https://github.com/espresso3389/pdfrx/assets/10806361/63153e59-3672-447b-bfff-88bf217575bd

**Comment by yhyh0** [comment] 2024-01-12 09:11
> @yhyh0 Yes, it is removed (at 0.4.3 [ab9c9d0](https://github.com/espresso3389/pdfrx/commit/ab9c9d00546f05d56203c8b1b43986a36a8079f2)) because it's too slow and could not be used in realistic apps. I'm now rewriting new text selection code that does not depend on Flutter's Selectable.
> 
> The last code is on [pdf_widget.dart on 70a92e](https://github.com/espresso3389/pdfrx/blob/70a92e2b4d9ad24b13209b712b4afa8ab6fa53da/lib/src/pdf_widgets.dart#L1068) and it may hopefully work with the latest pdfrx...

Wow you are fast! :+1: 70a92e doesn't work with the latest, but it's fine I will wait for the new release. 

Could there also be a callback, something like ```onTextSelected``` with the text and the event/rect(for showing a customized context menu)?

**Comment by espresso3389** [comment] 2024-01-12 09:14
@mlican
Could you explain me how did you realize that? Is it based on my implementation?

**Comment by mlican** [comment] 2024-01-12 09:31
> @mlican
> Could you explain me how did you realize that? Is it based on my implementation?

Yes, I made some optimizations on the text selector you wrote. I believe the performance is excellent, and the experience is fantastic. I'll provide you with the code for your reference later. I'm currently on my way home.

**Comment by mlican** [comment] 2024-01-12 12:56
> @mlican Could you explain me how did you realize that? Is it based on my implementation?

Separately create PDF text selection widget

```Dart
class PdfText extends StatefulWidget {
  const PdfText({
    required this.page,
    required this.pageRect,
    super.key,
  });

  final PdfPage page;
  final Rect pageRect;

  @override
  State<PdfText> createState() => PdfPageTextState();
}

class PdfPageTextState extends State<PdfText> {
  PdfPageText? pageText;
  List<Paragraph> paragraphList = [];

  Future initData() async {
    pageText = await widget.page.loadText();
    paragraphList = kMeansText(
        pageText?.fragments ?? []); // fragments convert to List<Paragraph>
    if (mounted) {
      setState(() {});
    }
  }

  @override
  void initState() {
    initData();
    // TODO: implement initState
    super.initState();
  }

  @override
  void didUpdateWidget(covariant PdfText oldWidget) {
    if (widget.page != oldWidget.page) {
      pageText?.fragments.clear();
      initData();
    }
    // TODO: implement didUpdateWidget
    super.didUpdateWidget(oldWidget);
  }

  @override
  Widget build(BuildContext context) {
    if (pageText == null) {
      return Container();
    }

    return _generateSelectionArea(
        context, pageText!.fragments, widget.page, widget.pageRect);
  }
  ......
}

```

`MouseRegion` in `_generateTextSelectionWidgets` needs to set `hitTestBehavior_generateTextSelectionWidgets` 

```Dart
MouseRegion(
            hitTestBehavior: HitTestBehavior.translucent, // Avoid mouse wheel anomalies
            cursor: SystemMouseCursors.text,
            child: _PdfTextWidget(
              registrar,
              fragment,
              fragment.charRects?.map((e) {
                return e
                    .toRect(height: page.height, scale: scale)
                    .translate(-rect.left, -rect.top);
              }).toList(),
              rect.size,
            ),
          )
```

**Comment by espresso3389** [comment] 2024-01-12 14:24
31a76abcabb3d68c55369306533a8559b9330f4d incorporates the @mlican implementation of PdfText as PdfPageTextOverlay.

But anyway, I'm working on another issue and will release new version soon this weekend I hope.

**Comment by espresso3389** [comment] 2024-01-12 19:02
Yet another implementation that runs far faster than the previous versions:

https://github.com/espresso3389/pdfrx/assets/1311400/771a197a-3a7e-44ab-9d6f-e3772e3a0eaa

The problem still remains is that when some refresh event occures such as zooming changes, the selection is cleared completely. I should do a little more work for that.

**Comment by espresso3389** [comment] 2024-01-13 16:03
[0.4.7](https://pub.dev/packages/pdfrx/versions/0.4.7) has incorporated the text selection code though it still have several issues as noted on [CHANGELOG.md](https://github.com/espresso3389/pdfrx/blob/dfb929b73852910690261098c231800978177e0f/CHANGELOG.md#047).

You can test it by [PdfViewerParams.enableTextSelection](https://pub.dev/documentation/pdfrx/0.4.6/pdfrx/PdfViewerParams/enableTextSelection.html).

**Comment by mlican** [comment] 2024-01-14 08:38
The character positioning in this PDF document is incorrect, and the text selection is abnormal. I'm not sure what the reason is.
[2326fb2d7c227a32f7f40446320f6de4.pdf](https://github.com/espresso3389/pdfrx/files/13930826/2326fb2d7c227a32f7f40446320f6de4.pdf)

**Comment by espresso3389** [comment] 2024-01-21 18:39
[0.4.17](https://pub.dev/packages/pdfrx/versions/0.4.17) add more consistency updates to text selection.
It makes text selection on mobile devices better.

**Comment by MarcVanDaele90** [comment] 2024-02-04 18:19
Is it correct that the current selection always starts at the beginning of a line? (see the attached recording from https://espresso3389.github.io/pdfrx/).  The selection is blazingly fast by the way! 

Would it be possible to support double click (select word) and triple click (select line).  Obviously, I can create a separate issue if you prefer

https://github.com/espresso3389/pdfrx/assets/90178346/f0787675-6193-442a-b3e0-d38b50d2cef3

**Comment by espresso3389** [comment] 2024-02-05 14:07
@MarcVanDaele90 I don't check the web's selection issue deeply, but it's just a web version (pdf.js) issue and other platforms correctly select words separately though they still have issues on selection...

**Comment by espresso3389** [comment] 2024-02-06 06:52
[0.3.48](https://pub.dev/packages/pdfrx/versions/0.4.38) has minor code changes on text selection.

**Comment by MarcVanDaele90** [comment] 2024-02-07 09:34
> @MarcVanDaele90 I don't check the web's selection issue deeply, but it's just a web version (pdf.js) issue and other platforms correctly select words separately though they still have issues on selection...

When I check the pdfjs example here https://mozilla.github.io/pdf.js/web/viewer.html , it seems to work fine so I'm not sure that this is just a pdfjs issue.  Can you have another look at this?

**Comment by espresso3389** [comment] 2024-02-08 05:34
@MarcVanDaele90 
> When I check the pdfjs example here https://mozilla.github.io/pdf.js/web/viewer.html , it seems to work fine so I'm not sure that this is just a pdfjs issue. Can you have another look at this?

Yes, I've been checking it. But I'm not sure what causes the issue. Same algorithm on cross-platform side.
Only the difference is web specific implementation but it just loads all the text fragments on the memory...

**Comment by MarcVanDaele90** [comment] 2024-02-09 08:23
Is it possible to create a small stripped down example that illustrates the issue?  Then I can also take a look and see if I can help.

**Comment by franzlst** [comment] 2024-03-11 08:56
@espresso3389 Thank you for coming so far with PDF support and the possibility to select text.

I wanted to point you to an issue, for which I'm not sure you are aware of (could be what you mean with "The problem still remains is that when some refresh event occures"): When I select text and what to right click if (in order to open the context menu, e.g. for copying), the selection is being reset and only the current line is selected. This can be reproduced with [your demo](https://espresso3389.github.io/pdfrx/).

Would be awesome if you find a solution here :-)

**Comment by espresso3389** [comment] 2024-03-11 09:08
Yes, I knew that. I've been struggling with the Flutter's behavior. Currently I don't understand the Flutter's selection architecture...

**Comment by MRYIN123** [comment] 2024-04-09 03:47
> 工作仍在进行中；但我正在努力解决 Flutter 的文本选择机制......
> 
>  视频.mp4

Whether you can release the callback of the selected text is this contextMenuBuilder

**Comment by espresso3389** [comment] 2024-05-04 13:09
@MRYIN123 It's a little old question but I think [PdfViewerParams.perPageSelectionAreaInjector](https://pub.dev/documentation/pdfrx/latest/pdfrx/PdfViewerParams/perPageSelectionAreaInjector.html) can do it. See [SelectionArea](https://api.flutter.dev/flutter/material/SelectionArea-class.html) for more.

**Comment by Aruljebaraj** [comment] 2024-05-07 06:57
while selecting text it create blue like box and selects random text

**Comment by espresso3389** [comment] 2024-05-07 07:04
> while selecting text it create blue like box and selects random text

Is selection area is correct?
For the copied text, the content may be broken depending on the PDF.

**Comment by espresso3389** [comment] 2024-06-26 08:50
The text selection feature itself is working though it is still experimental. And the issue is too large to break into. So anyway, I want to close the issue and further issues should be discussed on its dedicated issues.

**Closed by espresso3389** 2024-06-26 08:50 UTC
Labels: feature request

**Comment by espresso3389** [comment] 2024-07-03 17:22
Related: #180 On Flutter Web on mobile devices, unless `enableTextSelection: false` is set, panning/zooming by touch gesture never get enabled.
