### ISSUE TITLE
Error build for Android on Apple M3 Pro chip

### ISSUE THREAD

**Issue by reddeath1** [espresso3389/pdfrx#133] opened 2024-04-19 13:44 UTC
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':pdfrx:mergeDebugNativeLibs'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.MergeNativeLibsTask$MergeNativeLibsTaskWorkAction
   > 2 files found with path 'lib/arm64-v8a/libpdfium.so' from inputs:
      - /Volumes/xxx/build/pdfrx/intermediates/merged_jni_libs/debug/out/arm64-v8a/libpdfium.so
      - /Volumes/xxxx/build/pdfrx/intermediates/cxx/Debug/6yz3xf71/obj/arm64-v8a/libpdfium.so
     If you are using jniLibs and CMake IMPORTED targets, see
     https://developer.android.com/r/tools/jniLibs-vs-imported-targets
```

This happens only when building for android devices

**Comment by espresso3389** [comment] 2024-04-19 13:50
Duplicate of #8 and #82; search [mergeReleaseNativeLibs](https://github.com/espresso3389/pdfrx/issues?q=is%3Aissue+mergeReleaseNativeLibs+) instead of `mergeDebugNativeLibs`.

Add the following to `android/build.gradle`:

```
packagingOptions {
  pickFirst '**/libpdfium.so'
}
```

https://github.com/espresso3389/pdfrx/issues/8#issuecomment-1898225027

**Closed by espresso3389** 2024-04-19 13:50 UTC

**Comment by espresso3389** [comment] 2024-04-22 14:03
@reddeath1 Please open another issue for the iOS build problem.

**Comment by reddeath1** [comment] 2024-04-22 14:03
great, will do that shortly.
