### ISSUE TITLE
PDF lagging too much while scrolling 

### ISSUE THREAD

**Issue by dhruvhighspot** [espresso3389/pdfrx#196] opened 2024-07-01 04:36 UTC
While scrolling through the PDF, the response is too slow and laggy.
Detail:  You removed the bouncing animation in the previous version of PDFrx due to which the response is too slow and laggy.

**Comment by espresso3389** [comment] 2024-07-01 08:39
> Detail: You removed the bouncing animation in the previous version of PDFrx due to which the response is too slow and laggy.

Incorrect. At least, I didn't intended to do so.  What version do you say by "the previous version"?

Anyway, please let me know about your environment, `flutter doctor -v` and your actual device.

**Comment by dhruvhighspot** [comment] 2024-07-01 08:57
check this issue [link](https://github.com/espresso3389/pdfrx/issues/64)

**Comment by espresso3389** [comment] 2024-07-01 09:44
#64 is a duplicate of #61 and it is not fixed yet.

I'm not sure what removed the bouncing back animation but anyway I didn't intend it and furthermore, I didn't realize the change as far as I remember.

So, if your issue is #64, please describe your problem on #64 (or #61).

I close the issue because you mention #64 here.

**Closed by espresso3389** 2024-07-01 09:44 UTC
Labels: wait for response

**Comment by espresso3389** [comment] 2024-07-01 09:58
As a side note, basically "lagging too much while scrolling" has nothing to do with bouncing back animation. What's your point?
