### ISSUE TITLE
Reagarding animation 

### ISSUE THREAD

**Issue by dhruv9045** [espresso3389/pdfrx#75] opened 2024-02-14 18:14 UTC
This is issue occurs when we scroll up fast from 3rd or 4th page it touches the top and come back to 2nd or 3rd page and similar occuring in last pages.

Expected: when move fast to top page from where page start that will not come back to 2nd or 3rd page it should be stop where page start and similarly in pdf end when it should be stop at the end of the pdf not on second last or third last.

**Comment by espresso3389** [comment] 2024-02-14 18:29
Possible duplicate of #61?

**Comment by dhruv9045** [comment] 2024-02-14 18:38
Can you provide me some solution?

**Comment by espresso3389** [comment] 2024-02-14 18:39
I've been investigating the issue. Currently, no solution :(

**Closed** 2024-02-14 18:39 UTC

**Comment by dhruv9045** [comment] 2024-02-16 17:02
If you can add some other animation effect may be this will help
